kube-vip/kube-vip

Makefile, cmd/kube-vip.go, dockerfile/dockerfile, main.go, pkg/cluster/cluster.go, pkg/cluster/config.go, pkg/cluster/state.go, pkg/detector/interfaces.go, pkg/vip/address.go, pkg/vip/arp.go, pkg/vip/arp_unsupported.go
This initial commit contains all of the implementation details for:
- Build a multi-node cluster using RAFT
- Allocates/Deallocate a VIP using `netlink`
- Uses ARP to broadcast networking changes
- Creates example configuration
- Creates example manifest
=> Bare-Bones implementation

cmd/kube-vip.go, pkg/cluster/cluster.go, pkg/cluster/singleNode.go, pkg/kubevip/config_types.go, pkg/loadbalancer/manager.go
Adds the capability of having a single-node cluster(for k8s install)
=> SingleNode / LoadBalancer

cmd/kube-vip.go, pkg/cluster/cluster.go, pkg/kubevip/config_manager.go, pkg/kubevip/config_types.go
This removes the duplication of peers and has a seperate entry for remote and local peers
=> Simplification of configuration

pkg/kubevip/config_manager.go
Removes the need for a duplicate entry
=> Tidies old configuration

README.md, kubernetes-control-plane.md
This fixes #11 and separates out documentation to have a full document for Kubernetes load-balancing.
=> Documentation re-write

cmd/kube-vip.go
This should be set to `slice` to use a comma separated list.
=> Cli fixes to array

pkg/service/manager.go
The `os.Interupt` isn't the correct signal sent by Kubernetes when it shuts down a pod. This meant that restarting `kube-vip` would leak addresses on previous hosts, ultimately leading to hanging services.
=> This fixes a shutdown bug leaving addresses on hosts

pkg/loadbalancer/lb_tcp.go, pkg/loadbalancer/lb_tcp_consistent.go
Tidies the connectivity, section and improves logging for TCP load-balancing.
=> Tidy of TCP connectivity

Makefile, demo/deploy.yaml, example/deploy/0.1.4.yaml, pkg/loadbalancer/lb_udp.go, pkg/loadbalancer/manager.go, pkg/service/manager.go, pkg/service/services.go
This will correctly allocate load into a UDP back-end.. it is still WIP as it will just loop through backends.
=> Additional work with UDP

Dockerfile, Makefile, cmd/kube-vip-config.go, cmd/kube-vip-kubeadm.go, cmd/kube-vip-start.go, cmd/kube-vip.go, go.sum, pkg/cluster/cluster.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_manager.go, pkg/kubevip/config_types.go
This removes the need for an external file and moves everything into environment variables within a Kubernetes manifest.
=> Greatly simplifies the deployment of control plane

cmd/kube-vip-config.go
=> update arp config to be inline with help

cmd/kube-vip-config.go, cmd/kube-vip-kubeadm.go, cmd/kube-vip-start.go
=> update typos in configs

cmd/kube-vip.go
=> standardize default interface

pkg/vip/address.go
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>
=> fix lookup ordering: check if it's an IP before assuming address is a DNS Name

pkg/vip/arp.go
Both ARPRequest and ARPReply can be used to send gratuitous ARP, and network devices may only support either one of them.  Change to send request and reply alternatively.  
Fix #80
=> send arprequest and arpreply alternatively for gratuitous arp

Makefile
Updates the Makefile to build images with correct tag
=> Bumps Makefile to new release

cmd/kube-vip-start.go, cmd/kube-vip.go, pkg/cluster/clusterLeader.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go
=> Make port configurable

Makefile, README.md
=> Fix typo on README

cmd/kube-vip-start.go, docs/control-plane/index.md
Also adding the missing ddns command line option.
=> add docs for dns support

Makefile, cmd/kube-vip.go, pkg/kubevip/config_generator.go, pkg/service/services.go
This sets the default cidr `/32` for service type load-balancer
=> Default cidr

cmd/kube-vip.go, pkg/bgp/peers.go, pkg/bgp/types.go, pkg/kubevip/config_generator.go
=> This adds support for BGP Peer password

cmd/kube-vip-manifests.go, cmd/kube-vip.go, docs/manifests/kube-vip-em.yaml, go.mod, go.sum, pkg/cluster/clusterLeader.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/manager/manager_bgp.go, pkg/packet/bgp.go, pkg/service/manager_bgp.go
This allows the daemonset to consume the CCM secret, also enabled multi hop on the peers.
=> Multihop_and_use CCM Secret

cmd/kube-vip.go, docs/control-plane/index.md, docs/hyrbid/daemonset/index.md, docs/hyrbid/index.md, docs/hyrbid/services/index.md, docs/hyrbid/static/index.md, docs/index/index.md, docs/kubernetes/index.md, docs/manifests/kube-vip-em.yaml, docs/manifests/rbac.yaml, pkg/kubevip/config_generator.go, testing/create.sh, testing/lb_clean.sh, testing/teardown.sh, testing/testing.sh
This fixes the `bgppeers` subcommand from accidentally adding fake peers, and adds in the documentation around the "hybrid" mode.
=> This PR adds all of the updated documentation

docs/hyrbid/index.md
This adds in a notice about `/etc/hosts`
=> hostname_fix

docs/hybrid/static/index.md
=> Fix documentation, kube-vip alias for containerd

pkg/kubevip/config_generator.go, testing/testing.sh
This improves the testing, and tidies some confusing environment variable lookups.
=> Fixes to testing and config

docs/architecture/index.md
"expend" => "spend"
"expand" => "become/make larger"
=> change word expended to expanded

.github/workflows/main.yaml, .github/workflows/release.yaml
Related to https://github.com/plunder-app/plndr-cloud-provider/pull/32
Enjoy,
Vasileios
=> Adding the release actions

pkg/manager/watcher.go
This now adds the capability for the Password to be pulled from the annotations.
=> Bgp password support from annotations.

pkg/cluster/clusterLeader.go, pkg/cluster/singleNode.go
Fixes a missed error being checked.
=> Error fixes

README.md
=> Small Typo Improves in README.md

cmd/kube-vip-manifests.go, cmd/kube-vip.go, pkg/kubevip/config_generator.go, pkg/manager/manager_arp.go, pkg/manager/manager_bgp.go
=> Fixes DDNS

.github/workflows/release.yaml
Fixes: https://github.com/kube-vip/kube-vip/issues/211
=> feat: push images to ghcr

docs/hybrid/services/index.md, docs/manifests/controller.yaml
Services page documentation and controller deployment manifest updated as per comments in https://github.com/kube-vip/kube-vip-cloud-provider/issues/5
=> Update CCM docs and manifest

Makefile
Fixes the generation of Manifests.
=> Fixes manifest generation

.github/workflows/main.yaml, .github/workflows/release.yaml, Makefile, demo/Makefile, docs/architecture/index.md
This PR for adding support for the linux/ppc64le architecture support
=> Add support for ppc64le architecture

docs/flags/index.md, docs/install_daemonset/index.md, docs/install_static/index.md, docs/usage/EquinixMetal/index.md, docs/usage/k3s/index.md, docs/usage/kind/index.md
Moves documentation to the correct version and adds missing flags/environment variables.
=> Fixes Docs

pkg/kubevip/config_generator.go
- Tolerate more than just the node-role.kubernetes.io/master taint, this allows
the daemonset to schedule prior to CNI being deployed.
- Switch from using a nodeSelector to using nodeAffinity
- Allows scheduling even if the node label does not match the value (for the node-role label, the value is generally ignored).
- Add support for the control-plane node role rather than just master.
=> Update DaemonSet generation to improve scheduling

Makefile, cmd/kube-vip.go, docs/manifests/v0.4.0/kube-vip-arp-ds-lb.yaml, docs/manifests/v0.4.0/kube-vip-arp-ds.yaml, docs/manifests/v0.4.0/kube-vip-arp-lb.yaml, docs/manifests/v0.4.0/kube-vip-arp.yaml, docs/manifests/v0.4.0/kube-vip-bgp-ds.yaml, docs/manifests/v0.4.0/kube-vip-bgp-em-ds.yaml, docs/manifests/v0.4.0/kube-vip-bgp.yaml
This adds:
- Updated Makefile
- New Manifests
- Fix the `lb_port`
=> New release v0.4.0

pkg/loadbalancer/ipvs.go, testing/kubeadm/create.sh
This adds the following:
- Updated testing
- IPVS services are only created ONCE a backend exists.
Fixes #309
=> IPVS fixes

pkg/vip/ddns.go, pkg/vip/dhcp.go
=> fix ddns support

docs/flags/index.md
=> Adds missing flag/env for services interface

cmd/kube-vip-manifests.go, pkg/kubevip/config_generator.go
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
Fixes: https://github.com/kube-vip/kube-vip/issues/315
=> config: Use recommended labels in manifests

docs/manifests/v0.4.1/kube-vip-arp-ds-lb.yaml, docs/manifests/v0.4.1/kube-vip-arp-ds.yaml, docs/manifests/v0.4.1/kube-vip-arp-lb.yaml, docs/manifests/v0.4.1/kube-vip-arp.yaml, docs/manifests/v0.4.1/kube-vip-bgp-ds.yaml, docs/manifests/v0.4.1/kube-vip-bgp-em-ds.yaml, docs/manifests/v0.4.1/kube-vip-bgp.yaml
Generating the manifests for the 0.4.1 release.
=> docs: Generate manifests for 0.4.1

.github/workflows/ci.yaml, .github/workflows/main.yaml
Signed-off-by: yaocw2020 <yaocanwu@gmail.com>
There is no guarantee that the GitHub workflow will run on time.
=> Build and publish the main image every day

pkg/kubevip/config_manager.go
Signed-off-by: Chris Privitere <cprivite@users.noreply.github.com>
=> Don't check interface is up if it's loopback.

.github/workflows/main.yaml, .github/workflows/release.yaml, Makefile, demo/Makefile, docs/architecture/index.md
=> Add s390x arch support

pkg/cluster/service.go
Related issue: https://github.com/kube-vip/kube-vip/issues/382
=> The gratuitous arp should be sent periodically

cmd/kube-vip.go, pkg/cluster/service.go, pkg/vip/arp.go, testing/k3s/create.sh, testing/kubeadm/create.sh, testing/kubeadm/service.sh, testing/logging.bash
This tidies up all of the logging for the `kube-vip` testing, it also introduces some automated testing for the service creation and deployment of the cloud-provider.
=> Update to automated testing and clear msg

pkg/cluster/clusterLeaderElection.go
This PR is a proposed fix for issue #394
=> Set api-endpoint to host for incluster deployment

pkg/manager/watch_services.go
This ensures a node won't participate in the leaderElection when no local pods are found
`External Traffic Policy:  Local`
=> This enables local traffic policy

pkg/cluster/service.go
This adds routing table support to the leader when elected.
=> Adds a route if leader

cmd/kube-vip-manifests.go, cmd/kube-vip.go, pkg/bgp/peers.go, pkg/equinixmetal/utils.go, pkg/kubevip/config_manager.go, pkg/service/prom.go, pkg/vip/dhcp.go
Fixes various errors encounted when trying to "make"
go fmt errors
A golanglint-ci complaint about the prometheus server not having a ReadHeadersTimeout.
Signed-off-by: Chris Privitere <23177737+cprivitere@users.noreply.github.com>
=> Build-fixes

cmd/kube-vip.go, pkg/cluster/cluster.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/manager/manager_arp.go, pkg/manager/service_egress.go, pkg/manager/services.go, pkg/manager/servicesLeader.go, pkg/manager/watch_endpoints.go, pkg/manager/watch_services.go, pkg/vip/egress.go
Adds annotation watching for specific destination ports:
```
annotations:
kube-vip.io/egress: "true"
kube-vip.io/egress-destination-ports: udp:5060
```
=> Adds ports and namespaces

cmd/kube-vip-manifests.go, cmd/kube-vip.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/manager/manager.go, pkg/manager/manager_arp.go, pkg/manager/manager_bgp.go
This PR changes `EnableControlPane` ➡️ `EnableControlPlane`.
=> Fix typo in EnableControlPlane config option

testing/kubeadm/create_ctr.sh, testing/nodes
=> Adds some additional checking scripts

pkg/kubevip/config_environment.go, pkg/manager/manager_arp.go, pkg/manager/manager_table.go, pkg/manager/manager_wireguard.go, pkg/manager/servicesLeader.go, pkg/service/manager_arp.go
This ensures that all leaderElections are configurable.
Signed-off-by: thebsdbox <dan@thebsdbox.co.uk>
=> Fixes all leaderElection code to use config

pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_types.go, pkg/manager/service_egress.go
Fixes the issue with all traffic being "egressed".
Signed-off-by: thebsdbox <dan@thebsdbox.co.uk>
=> Adds the capability to exclude egress traffic

pkg/manager/servicesLeader.go, pkg/manager/watch_services.go
A bug meant that the active cache was being removed when a service was updated.. this keeps cache state separate from other functions.
Signed-off-by: thebsdbox <dan@thebsdbox.co.uk>
=> This fixes an issue with the cache being wiped

pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/manager/services.go
=> Adds capability to specify a subnet for the VIP

pkg/manager/manager_arp.go
Fixed the logic for ensuring egress rules are cleaned.
=> Fix to egress rules

pkg/manager/services.go
Makes the code clearer with set annotations.
=> Tidies the annotations

docs/usage/k3s/index.md
Fix broken documentation links
=> Update broken links in k3s docs

pkg/manager/watch_services.go
This ensures that the waitGroup isn't caught out by an additional `defer wg.Done()`
=> Fixes to negative waitgroup

pkg/manager/watch_services.go, testing/e2e/services/services.go
Fixes a missing `cancel()` for the service context, which was originally being mis-captured by a `done()`.
=> Adds services testing and fixes missing context

pkg/manager/watch_endpoints.go, pkg/manager/watch_services.go, testing/e2e/services/services.go
Ensures that leadership is restarted should a backend point/endpoint be modified or removed.
=> Ensures a leadership will be restarted

Makefile, testing/e2e/e2e/Dockerfile, testing/e2e/e2e/Makefile, testing/e2e/e2e/go.mod, testing/e2e/e2e/go.sum, testing/e2e/e2e/main.go, testing/e2e/services/kind-config.yaml, testing/e2e/services/kind.go, testing/e2e/services/kubernetes.go, testing/e2e/services/services.go
Adds e2e testing for services!
=> Adds e2e testing of services

docs/usage/k3s/index.md
Fix https://github.com/kube-vip/kube-vip/issues/525
PR for website https://github.com/kube-vip/website/pull/14
=> Fix the doc link

pkg/vip/address.go
Skip service security configuration for the service whose annotation kube-vip.io/ignore-service-security is true.
Related issue: https://github.com/kube-vip/kube-vip/issues/479
=> Add annotation kube-vip.io/ignore-service-security

pkg/manager/watch_services.go
Fix https://github.com/kube-vip/kube-vip/issues/570
=> Check activeServiceLoadBalancerCancel is nil or not before calling it

.gitignore, README.md, cmd/kube-vip.go, pkg/cluster/cluster.go, pkg/cluster/clusterLeaderElection.go, pkg/equinixmetal/eip.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_generator.go, pkg/manager/services.go, pkg/manager/watch_services.go, testing/kubeadm/create.sh, testing/kubeadm/create_ctr.sh
Hi,
This is a trivial PR fixing some misspellings found by [codespell](https://github.com/codespell-project/codespell).
Maybe it is worth adding it to the CI.
And also add `kube-vip` binary to `.gitignore`
=> chore: Spelling fixes

Dockerfile, Dockerfile_iptables
This fixes some vulnerabilities in the Iptables image.
=> This bumps the base images for vulnerabilities

docs/install_static/index.md
From the discussion on slack, this is the doc to use kube-vip for k0s HA deployment.
=> Add doc for static pods on k0s using k0sctl

testing/e2e/e2e_test.go
This allows you to specify your own kind images when doing e2e testing (control plane)
`K8S_IMAGE_PATH=kindest/node:v1.29.0 make e2e-tests` (for example)
=> Adds capability to use your own images for e2e

docs/flags/index.md
Ref: https://github.com/kube-vip/kube-vip/blob/69306d471c6a043253b29b7f1e8f78da08934701/pkg/loadbalancer/ipvs.go#L74
=> docs: fix directroute forwarding method

Makefile
Getting ready for the v0.7.0 release
=> Bumps the Makefile for a new release

.github/workflows/ci.yaml, Makefile, cmd/kube-vip.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, testing/e2e/e2e_test.go, testing/e2e/kube-vip.yaml.tmpl, testing/e2e/template.go
This allows you to modify the file used to speak locally with the kubernets API server.
=> Allows a configurable path to the kubernetes config

pkg/manager/watch_endpoints.go
* This fixes #723 
* It ensures that short hostnames are discovered correctly.
=> fix #723 and allow short hostnames as well

pkg/bgp/server.go
Ensures we have consistent `logrus` throughout the entire project.
=> Consistent logging

cmd/kube-vip-kubeadm.go, cmd/kube-vip-manifests.go
Fixes https://github.com/kube-vip/kube-vip/issues/749
=> fix: print manifests to stdout

pkg/kubevip/config_generator.go, testing/e2e/services/kubernetes.go
=> fix: Modify the ImagePullPolicy used by cli manifest

pkg/vip/address.go
https://github.com/kube-vip/kube-vip/issues/794
=> fix: add ddns address as a network

pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/manager/manager.go
Fixes a few linting issues breaking CI
=> fixes to linting

pkg/manager/manager_bgp.go
Fixes #815 
Errors were being ignored, leading to a `nil` being accessed.
=> Errors are being ignored

cmd/kube-vip-manifests.go, cmd/kube-vip.go
=> feat: generate VIPCIDR if not value is set

pkg/manager/services.go
Gates UPNP Port Forwarding behind the `kube-vip.io/forwardUPNP: "true"` annotation on the `LoadBalancer` Service. Services are not exposed via UPNP by default anymore.
Fixes: #839
=> Enable UPNP Port forwarding per service

pkg/kubevip/config_types.go, pkg/manager/instance.go, pkg/manager/services.go
Fixes UPNP forwarding only the port with the lowest numeric value.
Fixes: #951
=> UPNP: Assume that multiple ports can exist on a service

pkg/backend/backend.go, pkg/cluster/service.go, pkg/cluster/singleNode.go, pkg/k8s/client.go, pkg/loadbalancer/ipvs.go, pkg/manager/manager_table.go, pkg/manager/watch_endpoints.go, pkg/vip/address.go, pkg/vip/dns.go
This PR introduces Routing Table mode for Control Plane mode as described in #831.
=> Routing Table mode for Control Plane

pkg/cluster/clusterLeaderElection.go
=> initialize the config for the rwclient separately

pkg/manager/cluster.go, pkg/manager/manager.go
=> Fixed null pointer exception when IPVS loadbalancer is used

Makefile
=> Use the new release version in Makefile

pkg/manager/node_labeling.go
Fixes a small linting issue created with a previous merge
=> Fix linting issue

Makefile, pkg/manager/servicesLeader.go, pkg/manager/watch_services.go
Fixes a long standing issue with load balancers not being restarted correctly
=> Ensure watcher is restarted as expected

demo/server/main.go, pkg/bgp/peers.go, pkg/bgp/server.go, pkg/bgp/types.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/vip/util.go
=> Support for MP-BGP

pkg/kubevip/config_generator.go
=> drop all other capabilities

pkg/manager/services.go
This should fix #1107 
**Current behaviour**
When kube-vip tries to update the service status, if it will encounter an error other than conflict it will just return the error and delete the service from the manager. I don't think that's a proper behaviour, so decided to add a workaround for this.
**Changes**
1. I've replaced `retry.RetryOnConflict` with `retry.OnError` so it will try to retry the status update for every error. (not only for conflict errors). Configured this to wait to up to 30 seconds for success.
2. Removed deletion of the service after status update error from the manager. I think that there is no point of removing the service here. Even without status update other functions like ARP broadcasting etc. can still be going well. So now instead of deletion will only log an …
=> Less strict service status update error handling

pkg/manager/watch_services.go
This should fix #1110 
It turned out that when service was modified (e.g. by `kube-vip-cloud-controller` I believe) `vip.GarbageCollection` was always run and service's IP was deleted from the interface but was newer recreated. I've added condition that checks if IP addresses were changed during service's modification, so only unused addresses will be removed.
=> Fixed service IP address deletion on service modification bug

Makefile
=> Bump version to v0.9.1

Makefile
=> Bump version to v0.9.2

pkg/vip/address.go
This causes IPv6 source address selection according to RFC 3484 to ignore VIPs when choosing which address the host should use for egress communication.
Fixes #1198
=> Add VIPs as deprecated

pkg/services/egress.go
=> Unintentionally created duplicate functions that can't be used

pkg/manager/manager_table.go
Fix: ControlPlane was blocking main thread so Services could not start in parallel
=> change startup order of ControlPlane and Services
