kube-vip/kube-vip

cmd/kube-vip.go, pkg/cluster/cluster.go, pkg/kubevip/config_types.go
Either passing `-l` or `startAsLeader:true` makes the first node deployment much more simple
=> This simplifies starting the first instance as a leader

cmd/kube-vip.go
This generates a manifest with the `current` version of `kube-vip`
=> Fixes generation of manifest

kubernetes-control-plane.md
The `init` example uses the wrong arguments for the VIP and the API-servers, when compared to the configuration of `kube-vip`. This commit fixes this issue.
/cc @nickperry
=> This fixes the init command

cmd/kube-vip.go, pkg/kubevip/config_manager.go, pkg/kubevip/config_types.go
This adds a large number of flags to create a customised `kube-vip` configuration.
`-h`
```
--arp                       Use ARP broadcasts to improve VIP re-allocations
--interface string          Name of the interface to bind to (default "eth0")
--lbBackends strings        Comma seperated backends, format: address:port (default [192.168.0.1:8080,192.168.0.2:8080])
--lbBindToVip               Bind example load balancer to VIP
--lbName string             The name of a load balancer instance (default "Example Load Balancer")
--lbPort int                Port that load balander will expose on (default 8080)
--lbType string             Type of load balancer instance (tcp/http) (default "tcp")
--localPeer string          Settings for this peer, format: id:address:port (default …
```
=> Adds flags for creating configuration

Makefile, cmd/kube-vip.go, dockerfile/dockerfile, pkg/cluster/singleNode.go, pkg/kubevip/config_endpoints.go, pkg/loadbalancer/lb_tcp.go, pkg/service/manager.go, pkg/service/services.go, pkg/service/watcher.go
Huge changes:
`kube-vip` can now run in the cluster on worker nodes and be used to load balancer services to the outside world.
This is used through the `kube-vip service` sub command, additionally:
- `--configMap` points to the configMap used by the cloud-provider
- `--arp` enables the use of arp broadcasts
=> Kube-vip now works as an app LB

Makefile, example/deploy/0.1.2.yaml, go.mod, go.sum, pkg/service/manager.go
All auto-detect per namespace...
`sips whiskey`
This allows multiple `Kube-vip` in a namespace, with a leader holding the VIP and the load-balancing. In the event of maintenance or failure another will take leadership and host the VIP and load-balancing.
**TODO**: docs
=> InCluster VIP now uses leader election

kubernetes-control-plane.md
The binary /kube-vip must not be defined in version 0.1.5.
=> Update kubernetes control plane README for version 0.1.5

cmd/kube-vip-start.go
This ensures that a bad configpath is captured and a correct error message is reported..
```
> ./kube-vip start --config ./etc/kube-vip/config.yaml                                                                    kube-vip -> panic_fix ! ? RC=1
INFO[0000] Reading configuration from [./etc/kube-vip/config.yaml]
FATA[0000] Error reading [./etc/kube-vip/config.yaml]
>
```
This fixes #38
=> Fixes panic on bad configpath

cmd/kube-vip-config.go
Args instead of command, because the kube-vip binary is already executed
by the the image.
Use docker.io in image path, because docker.io is not always the
default registry.
Removing Env as it is currently empty and causes the sample not to work.
Add volume mount for the config file.
=> Update sample manifest

Makefile, cmd/kube-vip-kubeadm.go, go.mod, pkg/cluster/cluster.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_manager.go
This PR adds all of the functionality to use the kube-vip `kubeadm init` and `kubeadm join` commands. It also adds in client-go, to find all controlplane nodes.
=> Finalise join command

pkg/packet/bgp.go
This will add all peers found in the api to the BGP configuration.
=> Add multiple peers

cmd/kube-vip-kubeadm.go, cmd/kube-vip-start.go, cmd/kube-vip.go, pkg/cluster/cluster.go, pkg/cluster/clusterLeader.go, pkg/cluster/clusterRaft.go, pkg/cluster/singleNode.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/vip/address.go, pkg/vip/dns.go, pkg/vip/util.go
This PR fixes #79 and enables DNS support through an `address` flag/env/config. `vip_address` should is deprecated but will continue to work.
`address` accepts a DNS name or an IP, kube-vip will now run an IP updater that resolves the DNS Name and update the IP, this one will have a validity time, so that we don't have to care about cleanup whenever there is a DNS record update.
One thing small thing that is left to do is to cache the latest response in the `ipUpdater` struct so that we're able to update the IP in case of lookup failures.
Lastly, I will raise an issue to start refactoring our code base, so that we're able to introduce unit and integration tests
=> DNS support for kube-vip

cmd/kube-vip-kubeadm.go
The `kube-vip kubeadm init` should generate a pod spec, it's accidentally generating a daemonset spec. This fixes it.
=> kubeadm init should generate pod spec

pkg/kubevip/config_generator.go
I've no clue why the incorrect int parsing ended up in the code.
This fixes `i, err := strconv.ParseInt(env, 8, 0)` => **`i, err := strconv.ParseInt(env, 10, 32)`**
The incorrect `parseInt` would break larger numbers i.e. "15" becomes `13`
=> Fixes to int parsing

Makefile, pkg/cluster/singleNode.go, pkg/service/services.go
This removes the TCP LoadBalancer from the path and leaves it up to `kube-proxy` to handle the requests.
=> LoadBalancer Service changes

Makefile, go.mod, go.sum, pkg/service/manager.go, pkg/service/services.go
With upnp functionality enabled any loadbalancer will be exposed through a upnp gateway! Fixes #58 
Finally worked it out!
**Enabled UPNP in `kube-vip` manifest:**
```
env:
- name: enableUPNP
value: "true"
```
**Expose a service:**
```
dan@k8s01:~$ k expose deployment nginx-deployment --port=32380 --target-port=80 --type=LoadBalancer --name=nginx-loadbalance
service/nginx-loadbalance exposed
dan@k8s01:~$ k get svc
NAME                TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)           AGE
kubernetes          ClusterIP      10.96.0.1        <none>          443/TCP           21h
nginx-loadbalance   LoadBalancer   10.110.170.214   192.168.0.201   32380:32479/TCP   3s
```
**Check upnp logs on router:**
```
$ cat /var/log/upnp.leases | grep nginx …
```
=> This adds upnp functionality to kube-vip

pkg/kubevip/config_generator.go
This ensures the environment variables can be correctly used to manage the level of logging
=> This fixes logging through env

Makefile, cmd/kube-vip.go, pkg/kubevip/config_generator.go, pkg/service/manager.go, pkg/service/services.go, pkg/vip/address.go
This ensures that addresses attached to localhost `lo` can't proliferate and be picked up by things such as `kubelet`.
=> Interface scope

cmd/kube-vip-manifests.go
This ensures that we only check for a VIP if the control-plane is enabled.
=> Fixes to manifest gen

cmd/kube-vip-kubeadm.go, cmd/kube-vip-manifests.go, cmd/kube-vip.go, pkg/kubevip/config_generator.go, pkg/packet/utils.go
This allows a user to use the `--inCluster` flag and ensure that the generated manifest won't include the volumeMount for the external kubeConfig.
=> Manifest for inCluster

cmd/kube-vip.go, pkg/bgp/peers.go, pkg/bgp/types.go, pkg/kubevip/config_generator.go
The `--multihop` flag will enable BGP multi hop to BGP peers.
=> Enables BGP multihop

Dockerfile, cmd/kube-vip.go, go.sum, pkg/cluster/clusterLeader.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/manager/manager.go, pkg/manager/manager_bgp.go, pkg/packet/bgp.go, pkg/service/manager_bgp.go
This adds the capability for using a `projectID` instead of `projectName`... It also adds the capability for the ca-certs to exist inside the scratch container.
=> Now uses projectID from env/cli

cmd/kube-vip.go, pkg/bgp/peers.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go
This adds the `--bgppeers` flag that allows taking multiple peers in a comma seperated fashion:
```
kube-vip manifest pod --interface ens192 --vip 192.1.68.0.40 --bgp --controlplane --bgppeers 192.168.0.1:65000::true,192.168.0.2:6543::true
```
Fixes #132
=> Adds multiple peers from manifest

.github/workflows/ci.yaml, Makefile
- Bootstrap CI for kube-vip on GitHub Action
- Fixed deprecated call to go vet and add go mod tidy
=> Bootstrap continuous integration via GitHub Action

.github/workflows/ci.yaml
I use `act` locally to run GitHub Action and apparently it works
differently and on GitHub you have to run apt as sudo.
=> Fix permission access in GitHub Action

pkg/kubevip/config_generator.go
The serviceAccount is now only added with the `inCluster` flag
=> Fixes to serviceAccount

Makefile, cmd/kube-vip.go, docs/hybrid/daemonset/index.md, docs/hybrid/index.md, docs/hybrid/services/index.md, docs/hybrid/static/index.md, docs/manifests/rbac.yaml, pkg/bgp/hosts.go, pkg/cluster/clusterLeader.go, pkg/cluster/singleNode.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/manager/manager.go, pkg/manager/manager_bgp.go, pkg/manager/watcher.go, pkg/packet/bgp.go, pkg/packet/eip.go, pkg/service/manager_bgp.go
This now offers the `--annotations <provider>` flag, this is used to watch for BGP annotations being applied and will watch for: 
`<provider>/src-ip`
`<provider>/node-asn`
`<provider>/peer-ip`
`<provider>/peer-asn`
Once all these have been populated the watch ends and starts the BGP server
=> Annotations watcher

pkg/kubevip/config_generator.go
This updates the hardcoded secret name that is shared between kube-vip and the Equinix Metal CCM.
=> Fixes packet -> metal

docs/hybrid/index.md
=> fix "services" typo in hybrid docs

pkg/cluster/clusterLeader.go, pkg/manager/manager_arp.go
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>
This PR adds code to exit when the cleanup is done. This is especially useful when running on a single node cluster, where there's no other kube-vip pod to takeover the lease
=> leaderelection exit when the election is lost

pkg/manager/manager_arp.go
Error handling for the function StartLeaderCluster is not properly done.
Fixed #169 
Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>
=> Catch return value for StartLeaderCluster

pkg/packet/eip.go
IP assignment href returned from the API looks like:
```
/metal/v1/ips/97972920-f00b-453f-be1e-31eb53c19e38
```
It should be cleaned up to contain ID only, removing `/ips/` leads to
broken requests like:
```
2021/04/15 12:03:41 [DEBUG] DELETE https://api.equinix.com/metal/v1/ips//metal/v197972920-f00b-453f-be1e-31eb53c19e38
```
Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>
=> fix: unassign IPs correctly for Equinix Metal

Makefile, pkg/cluster/clusterLeader.go, pkg/cluster/singleNode.go
This change adds:
- Replace networking configuration when it's removed `systemctl restart networkd` etc..
- Regular ARP broadcasts for service load balancer messages.
=> Fixes interface on networking restart

Dockerfile, pkg/manager/watcher.go
This is a fix for #226, the logic around parsing annotations would never end if a BGP password wasn't supplied. The password is now optional.
This also fixes a debug message.
```
root@k8s:~# k logs -n kube-system   kube-vip-ds-8m9qk
time="2021-07-05T12:37:45Z" level=info msg="server started"
time="2021-07-05T12:37:45Z" level=debug msg="Using the internal Kubernetes token"
time="2021-07-05T12:37:45Z" level=info msg="Kube-Vip is waiting for annotation prefix [metal.equinix.com] to be present on this node"
time="2021-07-05T12:37:45Z" level=debug msg="10.80.96.25 / 65000 / 10.80.96.24 / 65530 \n"
time="2021-07-05T12:37:45Z" level=info msg="Exiting Annotations watcher"
time="2021-07-05T12:37:45Z" level=info msg="Starting Kube-vip Manager with the BGP engine"
```
=> Fixes the hang on BGP password

example/deploy/0.3.5.yaml
Add example manifest for kube-vip:v0.3.5 for deploying it as a daemonset for service `type: LoadBalancer`
=> Add example manifest for kube-vip:v0.3.5

Makefile, cmd/kube-vip-config.go, docs/control-plane/index.md, docs/hybrid/daemonset/index.md, docs/hybrid/static/index.md, docs/install_daemonset/index.md, docs/install_static/index.md, docs/k3s, docs/manifests/kube-vip-arp.yaml, docs/manifests/kube-vip-bgp.yaml, docs/manifests/kube-vip-em.yaml, docs/manifests/kube-vip.yaml, docs/usage/k3s/index.md, docs/usage/kind/index.md, example/deploy/0.1.2.yaml, example/deploy/0.1.3.yaml, kubernetes-control-plane.md, pkg/kubevip/config_generator.go
I've updated the unversioned docs and the config generation to use GHCR instead of docker.io, due to the rate limiting enforced by docker.io
I've made an assumption that by publishing the ghcr image that the project would perhaps be moving this way, feel free to close if I am mistaken.
NB: I got docker.io rate limited today and inspired to update this 🤣
=> chore: use ghcr default

Makefile
Using a subshell to get the latest version from `git tag`, to avoid further manual updates to the `Makefile`.
Also removing backticks in favour of POSIX compatability.
=> fix: makefile use latest git tag and be POSIX compat

go.mod, go.sum, pkg/manager/watcher.go, pkg/manager/watcher_test.go
`kube-vip` gets "stuck" waiting for the Metal annotations when they already exist on the nodes.
This change allows for the annotations on the node to be checked prior to enter the watch.
I've got a new environment spinning up now to test and will report back shortly.
=> fix: ensure node annotations are checked before watch

docs/hybrid/services/index.md, docs/usage/on-prem/index.md
Fix Doc typo
```
#kubectl get svc xxx  -o=jsonpath='{.spec.type}'
LoadBalancer
```
=> fix typo of ServiceType. There's no svc.spec.type = ServiceTypeLoadBalancer

cmd/kube-vip-start.go, pkg/cluster/clusterLeader.go, pkg/manager/manager_bgp.go, pkg/service/manager_arp.go, pkg/service/manager_bgp.go
in BGP mode this message appears with a typo
`time="2021-08-16T23:30:23Z" level=info msg="Starting the BGP server to adverise VIP routes to BGP peers"`
=> BGP mode spelling

pkg/manager/watcher.go, pkg/manager/watcher_test.go
Turns out I was never actually adding the password into the BGP configuration as the `append` happened **before** the password was added to the struct.
😢  computers... fixes #256
=> Fixes the broken logic in password parsing

pkg/packet/eip.go
Do not perform project lookup by name when projectID is defined in the config.
=> [metal] Use provided provider id in config if defined

pkg/manager/watcher.go
This sets not only the routerID but also the sourceIP of BGP peering when using annotations.
=> This will set source IP for BGP from annotations

pkg/cluster/clusterLeader.go
Use Equinix Metal credentials when available with EIP configuration
not just BGP configuration.
Signed-off-by: Jason DeTiberus <detiber@users.noreply.github.com>
=> Support use Equinix Metal credentials from config

cmd/kube-vip-config.go, cmd/kube-vip-kubeadm.go, cmd/kube-vip-manifests.go, cmd/kube-vip.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_generator_test.go, pkg/kubevip/config_types.go, pkg/manager/services.go
This allows an end user to specify a secondary interface that is used purely for services.
```
--interface eth0
--serviceInterface eth1
```
Or within the environment variables!
```
name: vip_serviceinterface
value: eth1
```
=> Implements a secondary interface just for services

docs/manifests/v0.3.9/kube-vip-arp-ds.yaml
Add hostAliases to kube-vip-arp-ds.yaml on v0.3.9.
Resolves issue where kubernetes name can not be resolved.
=> Add hostAliases to kube-vip-arp-ds.yaml on v0.3.9

pkg/cluster/clusterLeaderElection.go, pkg/cluster/service.go, pkg/loadbalancer/ipvs.go
Removes the hardcoded port from `6443` to what is specified as `port` usually still `6443` but can now be changed.
=> Allows setting an API server port

docs/usage/kind/index.md
KVVERSION needs to be preceeded with `$` for shell expansion of the variable.
`kubectl` is unlikely to be a binary in the current directory and is likely to be in `$PATH`
=> Various KIND documentation fixes

pkg/cluster/clusterLeaderElection.go
The current node watcher uses a label selector of the form `node-role.kubernetes.io/control-plane=`; this does not work correctly.
The label selector should be `node-role.kubernetes.io/control-plane` or `node-role.kubernetes.io/control-plane=true` to select the control-plane nodes.
Without these changes, the IPVS tables are never updated with the control plane nodes and clients making requests to the VIP will fail with a "connection refused" error.
```
$ kubectl get nodes -l node-role.kubernetes.io/control-plane=
No resources found
$ kubectl get nodes -l node-role.kubernetes.io/control-plane=true
NAME     STATUS   ROLES                       AGE   VERSION
pi4-00   Ready    control-plane,etcd,master   21h   v1.22.3+k3s1
pi4-01   Ready    control-plane,etcd,master   20h   v1.22.3+k3s1 …
```
=> Update label selector for control-plane nodes

pkg/cluster/service.go
After deploying a manifest created from
```sh
docker run --rm ghcr.io/kube-vip/kube-vip:v0.4.0 \
manifest \
daemonset \
--address 192.168.1.50 \
--inCluster \
--controlplane \
--services \
--arp \
--leaderElection \
--taint \
--enableLoadBalancer
```
the containers would enter a CrashLoopBackoff. The logs included the following panic:
```
time="2021-11-26T20:28:32Z" level=info msg="Starting IPVS LoadBalancer"
panic: runtime error: slice bounds out of range [:12] with capacity 0
goroutine 52 [running]:
github.com/cloudflare/ipvs.NewIP(...)
/go/pkg/mod/github.com/cloudflare/ipvs@v0.0.0-20210114211356-96b2597859b3/ip.go:25
github.com/kube-vip/kube-vip/pkg/loadbalancer.NewIPVSLB(0x0, 0x0, 0x192b, 0x1a, 0x0, 0x0)
/src/pkg/loadbalancer/ipvs.go:53 +0x580 …
```
=> Pass resolved VIP from Network.IP() to NewIPVSLB

cmd/kube-vip-config.go, cmd/kube-vip-start.go, cmd/kube-vip.go, docs/flags/index.md, pkg/cluster/service.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/loadbalancer/ipvs.go
Adds `lbForwardingMethod` / `lb_fwdmethod` flag so one could change it. Default to `Local`.
To give it a try: `docker pull ghcr.io/jbguerraz/kube-vip:0.4.1`
=> allow to configure the ipvs forwarding method

cmd/kube-vip.go, pkg/kubevip/config_manager.go
In some cases, kube-vip will start to serve before the interface is not
existed or not up. We should make sure the interface is valid.
We met the problem in the Harvester. Here is the issue https://github.com/harvester/harvester/issues/1681
Signed-off-by: yaocw2020 <yaocanwu@gmail.com>
=> Check interface

cmd/kube-vip.go, pkg/vip/util.go
The kube-vip chooses the default interface based on the default route. Once the default route changes, the default interface is very likely invalid. In this case, it would be better to crash the process. The pod will restart immediately if the kube-vip is deployed as a daemonset.
Signed-off-by: yaocw2020 <yaocanwu@gmail.com>
=> Monitor default VIP interface

pkg/vip/util.go
Fix comment issue: https://github.com/kube-vip/kube-vip/pull/339#discussion_r773918190
=> set route event log as debug level

pkg/manager/services.go, pkg/manager/watcher_test.go
This changes the `.status` update to use the retry, this should ensure we don't incur:
```
time="2022-02-17T14:31:06Z" level=error msg="Error updating Service [w4] Status: Put \"https://10.96.0.1:443/api/v1/namespaces/default/services/w4/status\": read tcp 192.168.0.44:35556->10.96.0.1:443: read: connection reset by peer"
```
=> Adds retry to status update

pkg/kubevip/config_manager.go
If I remember correctly, point-to-point interfaces will stay in UNKNOWN as well and never go to UP.
(Currently trying to use kube-vip to expose a Kubernetes API server on a wireguard network)
=> Don't check status on Point-To-Point interfaces

pkg/kubevip/config_manager.go
Previous commits addressed the issue of interface being incorrectly marked as
down for loopback (1a4465e) and point-to-point (051bb1f) interfaces by directly
passing the test when the interface is identified as any of those types. Both
commits failed to address the core issue, those interfaces (and many others) do
not publish their operational state resulting in the state UNKOWN. With this
commit, now interfaces with unknown status are accepted but the user is warned as
he needs to manually ensure that the interface is ready to handle traffic.
Fix #385.
=> Treat interfaces with unknown state as valid

go.mod, go.sum, pkg/manager/manager_arp.go, pkg/vip/dhcp.go
- The macvlan interface should not be deleted until the DHCP client has
released the IP.
- If the network manager in the operating system uses DHCP to obtain an IP
for the network card, it will occupy the DHCP client port. In this case,
the release function will fail because the unicast connection with the UDP
socket needs the same port. The solution depends on the pr https://github.com/insomniacslk/dhcp/pull/458
Related issue: https://github.com/harvester/harvester/issues/1835
Signed-off-by: yaocw2020 <yaocanwu@gmail.com>
=> Fix DHCP release bug

pkg/cluster/clusterLeaderElection.go
Signed-off-by: AxiomSamarth <sdeyagond@microsoft.com>
This is an update to the previous fix raised for issue #394 via PR #395 to make user consumption of inCluster `kube-vip start` command more seamless and easier.
=> set kubernetes:6443 as default hostname

cmd/kube-vip.go, pkg/kubevip/config_types.go, pkg/manager/manager.go, pkg/manager/manager_arp.go, pkg/manager/manager_bgp.go, pkg/manager/services.go, pkg/manager/servicesLeader.go, pkg/manager/watch_annotations.go, pkg/manager/watch_services.go, pkg/manager/watcher.go, pkg/vip/arp.go
This will add in a new capability to create a services watcher, on a new service all nodes will participate in a leaderElection (the lease being the service name). The leader will then advertise the VIP to the network, this will enable two things:
- Spread VIPs over ARP (layer 2), not an elegant solution.. but a solution non-the-less
- Allow external mode local, allowing direct traffic to pods (leader Election will be limited to nodes where pods are running locally)
=> Initial design of leaderElection per service

cmd/kube-vip-kubeadm.go, cmd/kube-vip.go, pkg/cluster/cluster.go, pkg/cluster/service.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_manager.go, pkg/kubevip/config_types.go, pkg/manager/instance.go, pkg/manager/manager.go, pkg/manager/manager_arp.go, pkg/manager/manager_table.go, pkg/manager/servicesLeader.go, pkg/vip/address.go, testing/kubeadm/create.sh
```
$ sudo ./kube-vip manager --table --services --interface lo
INFO[0000] Starting kube-vip.io [v0.4.4]                
INFO[0000] namespace [kube-system], Mode: [Routing Table], Features(s): Control Plane:[false], Services:[true] 
WARN[0000] the status of the interface lo is unknown. Ensure your interface is ready to accept traffic, if so you can safely ignore this message 
INFO[0000] prometheus HTTP server started               
INFO[0000] Starting Kube-vip Manager with the Routing Table engine 
INFO[0000] all routing table entries will exist in table [198] 
WARN[0000] unable to auto-detect namespace, dropping to [kube-system] 
INFO[0000] beginning services leadership, namespace [kube-system], lock name [plndr-svcs-lock], id [k8s04] 
I0629 16:05:00.381858     757 leaderelection.go:248] …
```
=> Table mode is now added to kube-vip

cmd/kube-vip.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go
This does the following:
- Manifest generation includes prometheus config
- Port customising is easier
- Prometheus is disabled with a blank address
=> prometheus changes

pkg/manager/instance.go, pkg/service/services_dhcp.go
Use IP instead of MAC address to determine if the virtual interface was already previously configured. This makes it possible to pre-define `kube-vip.io/hwaddr` annotation on a `LoadBalancer` and therefore allows defining a static DHCP lease for it.
You can test this by using `valtzu/kube-vip:v0.5.0` instead of `ghcr.io/kube-vip/kube-vip:v0.5.0`.
Closes #354
=> Allow fixed virtual MAC for DHCP VIPs

cmd/kube-vip.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/manager/watch_services.go
Currently, there's no way to restrict `kube-vip` to only acknowledge services with kube-vip's LB class `kube-vip.io/kube-vip-class`.
For example, if you have two services A and B:
- service A has lb class set to `kube-vip.io/kube-vip-class`
- service B no has lb class set
`kube-vip` will currently advertise IPs for both services A and B
With this change, if a user passes the `--lbClassOnly` flag, `kube-vip` will only advertise IPs for service A since it has `kube-vip`'s LB class but will ignore service B
If a user does not pass the `--lbClassOnly`, there will no change from the current behavior
=> Enable kube-vip to only respond to svc with kube-vip's lb class

pkg/manager/instance.go, pkg/vip/util.go
I was facing an issue when a new macvlan link was added as it was added with `nil` mac; letting the underlying software generate it. Therefore the DHCP request was being made with a non existent MAC and responses were never catched.
This PR adds one randomly generated MAC address when it's empty.
=> Add random MAC address generation for DHCP

pkg/manager/manager_arp.go, pkg/manager/service_egress.go
This ensures that the rules are only cleared ONCE on startup.
=> Fixes to where iptables are gc

pkg/cluster/clusterLeaderElection.go, pkg/cluster/service.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_types.go, pkg/manager/instance.go, pkg/manager/services.go, pkg/manager/servicesLeader.go, pkg/manager/watch_endpoints.go, pkg/vip/arp.go, pkg/vip/egress.go
This fixes an issue where services that weren't part of endpoint watches would generate another watcher whenever a service would "change" ... Also a lot of changes to debugging messages making output a lot clearer.. finally the capability to set the rate of ARP updates through the environment variable `vip_arpRate` in milliseconds.
=> logging and fixed an issue with multiple elections

pkg/cluster/clusterLeaderElection.go, pkg/manager/manager.go, pkg/manager/manager_arp.go, pkg/manager/watch_annotations.go, pkg/manager/watch_endpoints.go, pkg/manager/watch_services.go
This adds the following:
- A separate shutdown channel that when closed will ensure all goroutines that hold various contexts or retrywatcher shutdowns is triggered.
- Fixes an issue with slow shutdowns when kubernetes deletes a pod.
=> garbage collection for goroutines

docs/flags/index.md, pkg/bgp/peers.go, pkg/bgp/types.go
This series of patches allow kube-vip to advertise IPv6 VIPs and setup IPv6 peers. Also improve BGP support slightly.
See commit messages for detailed description.
=> Enable IPv6 peering and VIP advertisement and improve BGP support.

docs/manifests/rbac.yaml
Without this specific ClusterRole rule, kube-vip would not be able to listen for `endpoints` changes when deployed as a DaemonSet, thus causing the IP addresses not being announced and the following error message every second:
```
E1227 20:37:20.290479       1 retrywatcher.go:130] "Watch failed" err="unknown (get endpoints)"
```
=> Fix watching for endpoints RBAC rule

pkg/manager/watch_services.go
Ever since https://github.com/kube-vip/kube-vip/commit/36f42300c4e8024e9f819a73212ec1c23d1b522b,  `kube-vip` no longer responds to service deletion events, and thus does not release the VIP assigned to the network interface.
I tested the fix in production and it seems to behave correctly now:
```
time="2023-02-02T10:31:39Z" level=info msg="[LOADBALANCER] Stopping load balancers"
time="2023-02-02T10:31:39Z" level=info msg="[VIP] Releasing the Virtual IP [172.16.254.107]"
time="2023-02-02T10:31:39Z" level=info msg="Removed [b1756287-944c-492a-8554-0b5801134f88] from manager, [17] advertised services remain"
time="2023-02-02T10:31:39Z" level=info msg="service [util/translations-upload] has been deleted"
```
=> Fix service deletion not registering

cmd/kube-vip.go, pkg/manager/watch_endpoints.go, testing/e2e/services/services.go
Fixes a rare event where an endpoint would be recreated on the same node as the other one was still regarded as existing.. this would leave the endpoint updates in an inconclusive state.. now if the existing endpoint is deleted then the correct logic path will ensure a new leaderElection.
=> Fixes and testing for endpoints

cmd/kube-vip.go, docs/hybrid/daemonset/index.md, docs/usage/EquinixMetal/index.md, pkg/cluster/clusterLeaderElection.go, pkg/cluster/service.go, pkg/equinixmetal/bgp.go, pkg/equinixmetal/eip.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_generator.go, pkg/manager/manager_bgp.go, pkg/manager/watch_annotations.go, pkg/service/manager_bgp.go
This PR aims to fix issue https://github.com/kube-vip/kube-vip/issues/393
With this solutions it should work with both legacy and new annotations format since it looks for `metal.equinix.com/bgp-peers-0-<info>` or `metal.equinix.com/<info>` an as I understand it, it only works with one neighbour, so `metal.equinix.com/bgp-peers-1-<info>` annotations are not needed
The existing test https://github.com/kube-vip/kube-vip/blob/a92c536de25683f93161819c6630b62538166f16/pkg/manager/watcher_test.go#L67-L83 might be enough to check if this change works
=> check for new equinix ccm annotations

pkg/cluster/service.go, pkg/vip/address.go
Remove and re-add the address to the interface in the case that a duplicate address is detected. Without this change, kube-vip will take no corrective action, and the address will remain in dadfailed state. Removing and re adding the address causes duplicate address detection to happen again, hopefully successfully the next time. This behavior only applys to IPv6 addresses, as IPv4 addresses cannot get into the dadfailed state.
We suspect dadfailed happens when a new leader is elected and the old leader is too slow or fails to delete the IP address.
We attempted to add a test, but we find it impossible to reliably trigger a dadfailed state on the leader node. During manual testing we were occasionally trigger the scenario and see that this PR has the desired effect.
fixes: #523
=> Readd VIP if address has dadfailed flag

Makefile
Update tag to 0.5.11, also make the VERSION variable configurable
Fix https://github.com/kube-vip/kube-vip/issues/527
=> Update makefile to accept variable to update version

pkg/loadbalancer/ipvs.go
When IPv6 addresses are present in node.Status.Addresses, the IPVSLoadBalancer parses the addresses and attempts to add them as an IPv4 destinations. This results in useless entries in the service table that only hold the last 32 bits of address.
This change does two things:
- uses the appropriate address family when creating the service
- ignores backend addresses that use a different address family than the service
This avoids the immediate problem of using the wrong address family for IPv6 destinations and the useless entries in the service table.
#497 appears to report this problem
=> Use correct address family for ipvs destinations

cmd/kube-vip-start.go, pkg/bgp/server.go, pkg/cluster/clusterLeaderElection.go, pkg/manager/manager.go, pkg/manager/manager_bgp.go, pkg/manager/prom.go, pkg/service/manager.go, pkg/service/manager_bgp.go, pkg/service/prom.go
As described in #547, this PR adds the metrics to monitor the current state of the bgp sessions.
The port of the peer is hard coded, since it is not currently possible to change the port in kube-vip. As soon as this feature is implemented, the port will be accessible by using the peers state, similar to `GetNeighborAddress()`.
If this should be refactored later, just tell me and I append the 179 in the `peerDescription` directly.
Example metrics look like this:
```bash
bgp_session_info{peer="123.4.123.4:179",state="ACTIVE"} 0
bgp_session_info{peer="123.4.123.4:179",state="CONNECT"} 0
bgp_session_info{peer="123.4.123.4:179",state="ESTABLISHED"} 1
bgp_session_info{peer="123.4.123.4:179",state="IDLE"} 0
bgp_session_info{peer="123.4.123.4:179",state="OPENCONFIRM"} 0 …
```
=> [feat] Add bgp metrics (bgp_session_info)

cmd/kube-vip.go, pkg/cluster/cluster.go, pkg/iptables/iptables.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/manager/instance.go, pkg/manager/services.go, pkg/manager/watch_services.go, pkg/service/services.go, pkg/vip/address.go, pkg/vip/dhcp.go
Set IPTables rules to Restricts user access to ports other than the load balancer service port through the VIP. Moreover, considering DHCP and any other protocol port requirement, those ports should be reachable.
By the way, we also modify the watch_services.go to support changing service load balancer IP.
IPTables Rules example:
```
-A INPUT -d 172.19.104.147/32 -p tcp -m tcp --dport 80 -m comment --comment "default/primary kube-vip load balancer IP" -j ACCEPT
-A INPUT -d 172.19.104.147/32 -p udp -m udp --dport 68 -m comment --comment "default/primary kube-vip load balancer IP" -j ACCEPT
-A INPUT -d 172.19.104.147/32 -m comment --comment "default/primary kube-vip load balancer IP" -j DROP
```
Related issue: https://github.com/kube-vip/kube-vip/issues/479
=> Set iptables rules to restrict user access to ports other than the load balancer service port through the VIP

pkg/equinixmetal/bgp.go
The Equinix Metal API integration was missing support for BGP session passwords so this PR adds the BGP password parameter.
=> Add BGP password support for Equinix Metal

pkg/manager/watch_annotations.go
Using Equinix Metal annotations was limited to only the first BGP peer. This PR adds support for multiple BGP peer by looking at all bgp peer node annotations.
Fixes #543
=> Add support for multiple BGP peers when using Equinix Metal annotations

Dockerfile_iptables, entrypoint_iptables.sh
Reverts kube-vip/kube-vip#502
Not required.. this was implemented in a PR ages ago to auto-detect iptables/nftables.
=> Revert "adding iptables-wrappers script to entrypoint"

cmd/kube-vip.go, pkg/cluster/clusterLeaderElection.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go
At the moment the lease name for leader election is hardcoded to 'plndr-cp-lock'. If you want to run multiple kube-vip instances in the same namespace this will conflict.
Code has not been tested yet since the testing instructions in CONTRIBUTING.md do not work and I did not manage to find any other testing scripts in the short time that I looked.
=> Use configurable LeaseName instead of hardcoded

pkg/cluster/clusterLeaderElection.go, pkg/manager/manager_bgp.go
Hi kube-vip, in order to implement a BGP based VIP with leader election, I had to make this tweak.
I have tested this on a test cluster in control plane however a notable deficiency in my testing is that I have not tried this change in services mode. It does not look like there is an automated test for BGP so I could use some advice on how to proceed with this change- Thank you!
=> enable leaderelection for bgp in CP mode

pkg/cluster/clusterLeaderElection.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_types.go
It would be nice to be able to watch for changes for certain Lease resources, and not others. This PR adds the ability to add annotations to the Lease resources being created by kube-vip, allowing for easy filtering of the leases.
=> Allow specifying annotations for created Lease resources

pkg/manager/watch_services.go
We re-implement the `activeService` that had been removed  ¯\_(ツ)_/¯ .. We now can watch for both an active service (to ensure we don't start a leader Election twice) and ensure we don't also create an additional watched. Multiple of these creates API issues and leads to chaos..
=> This makes sure we check if a services is active

Makefile
It looks like when v.0.6.1 was cut, the makefile wasn't updated to reflect the new version. This affects manifest generation (not too sure the implications beyond this).
=> Updating version in makefile

cmd/kube-vip.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/manager/manager_arp.go, pkg/manager/node_labeling.go
This feature is related to #611, to configure the _**CiliumEgressGatewayPolicy**_ *EgressIP* correctly.
As this is not a very common usage for this project, there is a default disabled configuration flag added, `enable_node_labeling`.
The *ClusterRole* also needed patch rights to adjust the node labels.
Let me know what you think about the change, and where is the best place to document this feature.
Thank you!
=> ARP: Add node labeling for ARP mode DaemonSet deployment.

cmd/kube-vip.go
Hi,
This is a trivial PR for handling the prometheus root path `/`.
Currently,
```console
curl localhost:2112
404 page not found
```
With this PR,
```console
curl localhost:2112
<html>
<head><title>kube-vip</title></head>
<body>
<h1>kube-vip Metrics</h1>
<p><a href="/metrics">Metrics</a></p>
</body>
</html>%
```
=> prometheus: Handle root path

.github/workflows/ci.yaml, .gitignore, Makefile, pkg/kubevip/config_environment.go, pkg/manager/watcher_test.go, testing/e2e/e2e_suite_test.go, testing/e2e/e2e_test.go
Maybe there was a reason to not run unit tests but I thought it could be useful to run what we already have and it makes it easier for folks to add more as they write new code.
A couple extra things:
* Fixed 2 broken tests
* Separated unit tests, e2e tests, linter and scans in different jobs so they run concurrently.
=> Enable unit and e2e tests in CI

pkg/cluster/service.go
This ensures that kube-vip will restart itself in the event of failing to apply addresses to an interface.
=> Call fatal when interface fails

testing/e2e/e2e_suite_test.go, testing/e2e/etcd/election_test.go, testing/e2e/etcd/etcd_suite_test.go, testing/e2e/etcd/kubelet.yaml, testing/e2e/ip.go
In order to run the kubelet in kind containers on the vms provided by github, the kubelet needed some extra configuration.
I also added some setup for the kind network so the the etcd tests don't depend on being run together with the other e2e tests.
=> Fix etcd e2e tests in GitHub actions

.github/dependabot.yml
This adds a [dependabot](https://github.com/dependabot) configuration that checks for new updates on go dependencies and github workflows on a weekly base.
=> .github: Add a dependabot config

docs/usage/kind/index.md
Hey @thebsdbox, all,
I have been trying kube-vip for the first time. Started with `kind` and realized that the usage instructions (if followed as-is) doesn't quite get the LB in a working state.
The RBAC settings were missing and hence the daemonset was never reaching out to running state.
Sorry if that is obvious step, but I would have a better user journey if it was mentioned, hence this PR.
Cheers.
=> Added create rbac settings section for kind deployment

pkg/manager/instance.go, pkg/manager/manager_arp.go, pkg/manager/manager_table.go, pkg/manager/manager_wireguard.go, pkg/manager/services.go, pkg/manager/servicesLeader.go, pkg/manager/watch_services.go, testing/e2e/services/kind.go, testing/e2e/services/kubernetes.go, testing/e2e/services/services.go, testing/e2e/services/tests.go
As a preliminary step towards dualstack support, I've made some changes to allow handling the case where the field `metadata.annotations["kube-vip.io/loadbalancerIPs"]` has multiple IPs.
Right now, there are some cases where I couldn't quite figure out the best UX for multiple loadbalancer IPs for a single service, so for now I'm only supporting dualstack LoadBalancer services in the EnableARP configuration of kube-vip and leaving cases like DHCP, EnableBGP, and uPnP as supporting only one LoadBalancer IP per service. Also egress only supports the first IP in the list of loadbalancer IPs.
I think I'd like to do some more cleanup for this PR, but I've added a test for a dualstack LoadBalancer service and it passes now:
```
time="2023-12-16T04:02:44Z" level=info msg="🧪 ---> testing …
```
=> Dualstack support for Loadbalancer Services

docs/flags/index.md, pkg/bgp/peers.go, pkg/bgp/types.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/manager/watch_annotations.go, pkg/manager/watcher_test.go
In certain scenarios, it's easier to change the BGP timer settings from the kube-vip side rather than configuring the routers' peer-group timer settings for kube-vip. This is desirable if the router defaults are higher than what we'd like to configure on the kube-vip side for the purpose of quickly reacting to a node down or network partition.
This change adds two new env vars for configuring these settings during the start of peering.
I was able to validate on my local deployment, that the switch side was picking up the modified timer settings.
```
kube-vip manifest yaml envvars
...
- name: bgp_hold_time
value: "9"
- name: bgp_keepalive_interval
value: "3"
...
Router `show ip bgp neighbors`
...
BGP neighbor is x.x.x.x, remote AS xxxx, internal link
BGP version 4, remote router ID …
```
=> Add config options for BGP timers

cmd/kube-vip-manifests.go, cmd/kube-vip.go, go.mod, pkg/k8s/client.go, pkg/k8s/client_test.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/manager/manager.go
There is now an option for the Kubernetes client to auto-detect the IP addresses in the API server certificate. This should allow us to find an address that works with the cert and establishes the connection.
=> Updates to the client to auto-detect

go.mod, go.sum, pkg/loadbalancer/ipvs.go, pkg/loadbalancer/ipvs_test.go
moved from some internal representations of IP addresses to the `net/netip` library.
=> fixes to the new ipvs import

cmd/kube-vip.go
* add cli-options to also set the hold_time and keep_alive_interval which were only possible by environment variables.
* it also uses the defaults of hold_time `30` to keep_alive_interval `10` which should be ok for most environments to start with.
https://github.com/kube-vip/kube-vip/pull/695
It needs to be documented on https://github.com/kube-vip/website as well
=> Added cli-options for bgp holdtime and keepalive

cmd/kube-vip.go, pkg/cluster/cluster.go, pkg/cluster/clusterDDNS.go, pkg/cluster/clusterLeaderElection.go, pkg/cluster/service.go, pkg/cluster/singleNode.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/manager/instance.go, pkg/manager/manager_arp.go, pkg/manager/service_egress.go, pkg/manager/services.go, pkg/manager/servicesLeader.go, pkg/manager/watch_endpoints.go, pkg/manager/watch_endpointslices.go, pkg/manager/watch_services.go, pkg/vip/address.go, pkg/vip/dns.go, pkg/vip/egress.go, pkg/vip/util.go, testing/e2e/e2e_test.go, testing/e2e/ip.go, testing/e2e/services/kind.go, testing/e2e/services/tests.go
This PR introduces minimal implementation for DualStack support. Main changes are:
- `status.loadbalancer.ingress` can be used to obtain service IP address if `kube-vip.io/loadbalancerIPs` annotation is not set
- way to disable updates of status.loadbalancer.ingress , so kube-vip can be used alongside other loadbalancers as e.g. routing table configuration service (configured with `DisableServiceUpdates` flag).
- support for enpointslices (this will be merged alongside #720)
- egress can be now configured for IPv6
- DNS lookup can now return IPv4, IPv6 or both (configured with `DNSMode` flag).
This PR has to be thoroughly reviewed and tested as I have no means to test all the possible configurations.
=> Minimal implementation of DualStack Services support

cmd/kube-vip-kubeadm.go, cmd/kube-vip-manifests.go, pkg/equinixmetal/bgp.go
When I was looking at the source code, I noticed that print was being used here, and I felt it would be better to change it to log output.
=> fix: Using log instead of fmt.print

pkg/loadbalancer/ipvs.go
After upgrading IPVS to 0.10.1, it is necessary to specify the Netmask.
If it is necessary to parse the netmask from a specific location, I will also update this PR. Comments are welcome.
Fix https://github.com/kube-vip/kube-vip/issues/755
Fix https://github.com/kube-vip/kube-vip/issues/752
=> Fix IPVS service error: netlink receive invalid argument

cmd/kube-vip.go, pkg/cluster/cluster.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_types.go, pkg/manager/instance.go, pkg/manager/manager_table.go, pkg/manager/watch_endpoints.go, pkg/manager/watch_services.go, pkg/vip/address.go
This PR introduces a possibility to clean reduntant routes created in routing table mode as described in #762 
Created routes will be tagged using `protocol` as explained in [ip-route man](https://man7.org/linux/man-pages/man8/ip-route.8.html) (value `protocol RTPROTO`) which is configurable using `routingProtocol` flag (defaults to ~~`198`~~ `248`, ~~same as table~~).
On every kube-vip start, if `cleanRoutingTable` flag is set `true`, _after 10s of initial delay_, all routes from the configured table that have protocol set to the same value as `routingProtocol`, will be get from node and checked against watched services. If no service will have LB IP same as the route `dst` field, the route will be deleted.
=> Added possibility to remove redundant routes

pkg/manager/service_egress.go, pkg/manager/service_egress_test.go
The function `getSameFamilyCidr` is a bit buggy, and introduced an issue where people manually specify ranges in the kube-vip config. This change allows the function to work, but also restores the default behaviour too.
=> fixes a bug that wouldn't return CIDRs for egress

testing/e2e/e2e_test.go
…ne VIP
Fix https://github.com/kube-vip/kube-vip/issues/771
Assume VIP is routable even if API server returns 500, since that means VIP is routable, it just might be because etcd is glitching.
Another way to fix is to increase the timeout, but I think better not to increase that since 30s is already a long time
considering the default config
```
- name: vip_leaseduration
value: "5"
- name: vip_renewdeadline
value: "3"
- name: vip_retryperiod
value: "1"
```
=> Fix flaky e2e test

pkg/loadbalancer/ipvs.go, pkg/loadbalancer/ipvs_test.go
Fix https://github.com/kube-vip/kube-vip/issues/781
=> Fix netmask of ipvs to consider ipv6 case

cmd/kube-vip.go, pkg/cluster/cluster.go, pkg/cluster/service.go, pkg/iptables/iptables.go, pkg/iptables/version.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/loadbalancer/ipvs.go, pkg/manager/manager.go, pkg/sysctl/sysctl.go, pkg/vip/address.go
| Configuration Key                | Type    | Unit | Default | Options     | Required |
|----------------------------------|---------|------|---------|-------------|----------|
| `backend_health_check_interval`  | int     | seconds    |    5     |             | No       |
| `iptables_backend`               | string  |      |         | `nft`, `legacy` | No       |
| ~~`masquerade_mark`~~                | string  |      | `0x1119`|             | No       |
* `iptables_backend`: Although we already have egress_withnftables, it is not sufficiently clear for users who want to configure`masquerade` mode. The newly added field does not require user specification by default; the program will determine it automatically.
* ~~`masquerade_mark`~~: we change iptable rule to `iptables -t nat -A …
=> Add masquerade mode

Dockerfile_iptables
Adding `iptables-legacy` package for backward compatibility as Alpine 3.19 defaults to nft and legacy symlinks no longer exist.
Related issue: #808
=> fix: add iptables-legacy package

cmd/kube-vip.go, pkg/loadbalancer/ipvs.go, pkg/manager/manager.go, pkg/utils/utils.go, pkg/vip/address.go
- Fixes:
-  Set ipvs conntrack enablement after IPVS kernel module validation, otherwise with current code, it will raise error like
```
time="2024-04-04T12:11:15Z" level=info msg="Starting kube-vip.io [v0.7.2]"
time="2024-04-04T12:11:15Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[false]"
time="2024-04-04T12:11:15Z" level=info msg="sysctl set net.ipv4.vs.conntrack to 1"
time="2024-04-04T12:11:15Z" level=fatal msg="failed to open file: open /proc/sys/net/ipv4/vs/conntrack: no such file or directory
```
-  when controlplane backend health checks should regard kubeconfig either from "/etc/kubernetes/admin.conf" when kubevip running as a kubeadm Pod or incluster service account when kubevip running as a daemonset.  Otherwise it will …
=> Fixes on masquerade forwarding mode

pkg/manager/instance.go, pkg/manager/services.go
The annotation `kube-vip.io/serviceInterface: ens160`  will now mean that the service will be bound to a specific interface `ens160` in this example. 
cc /@yankcrime
=> Adds annotation support for service interfaces.

example/deployment.yaml, example/service-interface-annotation.yaml, example/service.yaml, pkg/cluster/service.go, pkg/manager/instance.go, pkg/manager/services.go
Both the default behaviour (defaulting to the original or services Interface) is confirmed, in the event of an annotation such as:
```
metadata:
name: nginx-interface-ens192-service
annotations:
kube-vip.io/serviceInterface: ens192
```
then we can see:
```
(svcs) adding VIP [192.168.0.217] via ens192 for [default/nginx-interface-ens192-service]
<on node>
$ ip a show dev ens192
3: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
link/ether 00:50:56:8c:77:a5 brd ff:ff:ff:ff:ff:ff
altname enp11s0
inet 192.168.0.217/32 scope global ens192
```
Looking at the applied service:
```
$ kubectl describe svc  nginx-interface-ens192-service
...
Annotations:              kube-vip.io/loadbalancerIPs: 192.168.0.217
kube-vip.io/serviceInterface: ens192 …
```
=> Examples and fixes to annotation interface

demo/server/main.go
The usage of `strings.ToLower` in the demo server implementation is unnecessary because it's a hard-coded lowercase string already. 
Tiny fix, I know, but it was really bugging me.
=> fix: unecessary string modification

pkg/manager/watch_services.go
=> fix: set service's uid in activeService map for inactive services

pkg/manager/manager_table.go, pkg/manager/watch_endpoints.go
This PR should fix route deletion issue in routing table mode as described in #823.
The issue was, that when a service with no endpoints was created, kube-vip deleted the route as there were no endpoints but did not check if any other service references the same loadbalancer IP.
Now, when deleting the routes, kube-vip will scan all the known services to check if more than one service references the route that is being deleted. If so, it will cancel the deletion.
=> Fixed route deletion when route is used by more than one service

pkg/cluster/service.go
* When running kube-vip without `vip_leaderelection` or `svc_election` it only deletes IPs from interfaces but never deleted the Route from the RoutingTable in Table Mode
* This change would introduce a bit of cluttering in the logs, when Routes are not installed on a particular node but kube-vip is trying to delete the route for a service when in TableMode
* Functionally it should not break any existing setup using TableMode it just cleans Routes after the Service gets deleted
=> [Hotfix] Routes get not deleted when kube-vip is running without LeaderElection/ServiceElection in Table Mode

cmd/kube-vip.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_types.go, pkg/manager/watch_services.go
This PR introduces new behavior for LoadBalancer Class Name service filtering. With this new implementation only services that have LB class name set to the value configured in kube-vip (`LoadBalancerClassName` flag) will be processed. This is consistent with implementation in e.g. [MetalLB](https://github.com/metallb/metallb/blob/main/internal/k8s/controllers/service_controller.go#L159) or with how the ingress classes behave.
However this might be a braking change, so it is implemented (for now) as an option. 'Legacy' behavior is a default and can be disabled by setting `LoadBalancerClassLegacyHandling` config flag to `false`. In one of next releases this could become a default setting, and then legacy behavior could be removed altogether.
Fixes #851
=> New service class filtering behavior

pkg/kubevip/config_generator.go
`--prometheusHTTPServer ""` will now create
```
- name: prometheus_server
```
with no `- value`, which should stop prometheus from starting.
=> This allows prometheus configuration to be specified in the cli

pkg/kubevip/config_environment.go
Current Behaviour:
kube-vip does not start.
```
time="2024-06-25T11:45:39Z" level=fatal msg="strconv.ParseInt: parsing \"2347908769\": value out of range"
```
With this fix it should start.
References:
* [rtnetlink.h](https://github.com/torvalds/linux/blob/55027e689933ba2e64f3d245fb1ff185b3e7fc81/include/uapi/linux/rtnetlink.h\#L354C15-L354C25) 
* RT_TABLE_MAX=0xFFFFFFFF
=> [Bugfix] Parse the routingTableID correctly 

.github/workflows/ci.yaml, Makefile, cmd/kube-vip-manifests.go, pkg/kubevip/config_generator.go
This adds:
- CI test for manifests
- Ensures Manifests are created without a VIP (control plane) #885
- No `.status` for daemonset #876
=> Manifest fix

pkg/manager/instance.go
When using DHCP for LB services, the resulting IP was assigned to the `serviceInterface` while most (not all) DHCP communication was done through a per-service `macvlan` interface that is created on demand.
This has been the cause of DHCP lease renewal failures for some users, as the response packets from the server never reached kube-vip. For more details, see issue #871.
To remedy this, the primary interface used for a service is now being set to the `macvlan`. Consequently, the IP address is also assigned to it.
As a result, all traffic related to an LB service (DHCP or not) is now originating from and sent to the per-service `macvlan` interface that is tied to the user-configured `serviceInterface`.
Fixes #871
=> Change service interface to `macvlan` when using DHCP

pkg/kubevip/config_manager.go, pkg/manager/instance.go
This PR fixes #903 
It introduces feature to automatically discover proper networking interface for the service based on the service's loadbalancer's IP.
To enable this feature `vip_servicesinterface` should be set to value `auto` (to enable it globally) or `kube-vip.io/serviceInterface` annotation should be set to `auto` to enable this for selected service.
=> Auto network interface discovery for services

pkg/manager/instance.go, pkg/manager/service_egress.go, pkg/manager/services.go, pkg/manager/watch_endpoints.go, pkg/vip/util.go, testing/e2e/e2e/main.go, testing/e2e/services/kind.go, testing/e2e/services/kubernetes.go, testing/e2e/services/services.go, testing/e2e/services/tests.go
The original Egress functionality with IPv4 only, this PR adds the capability for egress addresses to be IPv6.
An additional annotation is required, and the `rbac.yaml` will need updating with pod-list/get in order to auto-detect the pod/service CIDRs.
=> This adds ipv6 egress & test

cmd/kube-vip.go, pkg/cluster/cluster.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/vip/address.go
Fixes https://github.com/kube-vip/kube-vip/issues/922
This PR adds a new flag to allow for overriding the current default behavior when creating a kube VIP on the localhost (lo) interface, which automatically sets the scope to `host`. Enabling the new `loInterfaceGlobalScope` flag will prevent kube-vip from setting a `host` scope and will instead use the `global` scope.
=> Add loInterfaceGlobalScope flag for enabling global scope for vip lo interface

pkg/backend/backend.go, testing/e2e/e2e_test.go, testing/e2e/ip.go, testing/e2e/kube-vip-routing-table.yaml.tmpl
This PR is a followup for #957 
It adds simple E2E tests for control-plane in routing table mode.
While writing the tests I've found an issue with IPv6 handling that should be fixed now as well.
=> Added e2e tests for control-plane in routing table mode, fixed IPv6 issue

pkg/cluster/service.go
This should fix #971 
It seems I've messed up NDP on one of previous updates. Due to nested for loops it seemed to try to advertise IPv6 on IPv4 `network`, so NDP responder was not created and therefore `nil`.
=> Fixed NDP responder

pkg/backend/backend.go, pkg/cluster/clusterLeaderElection.go, pkg/k8s/client.go, pkg/manager/manager.go, pkg/manager/watch_annotations.go, pkg/manager/watch_endpoints.go, pkg/manager/watch_endpointslices.go, pkg/manager/watch_services.go, testing/e2e/services/tests.go
This should fix #930 
Between v0.6.4 and v0.7.0 some k8s client changes were introduced. One of those changes was introduction of client timeout set by default to `10s`.
The same client is used by RetryWatcher, and it seems that this timeout makes retry watcher to restart every 10s, which creates a a lot of logs.
I've added separate k8s clientset which does not use timeout value  for RetryWatcher to use.
=> Fixed retry-watcher timeout issue

Makefile, pkg/kubevip/config_environment.go, pkg/manager/manager_arp.go, pkg/manager/manager_table.go, pkg/manager/service_egress.go, pkg/manager/watch_endpoints.go, pkg/manager/watch_services.go, pkg/vip/egress.go, testing/e2e/e2e_test.go, testing/e2e/services/controlplane.go
This PR fixes #966 
It introduces a few changes:
1. Egress rules should be now deleted properly in service-election routing table mode when service is deleted, election is lost or kube-vip's pod is terminated.
2. Auto service/pod CIDR discovery will now not be used if `egress_servicecidr` and/or `egress_podcidr` is defined.
3. A minor change in the e2e tests - docker image will be now loaded only after the cluster was created. (this can be discarded in favor of better e2e test fix if possible. Added that just to run the tests for now.)
=> Egress rules deletion fix

go.mod, go.sum, pkg/manager/manager.go, pkg/manager/manager_arp.go, pkg/manager/manager_wireguard.go, pkg/manager/services.go, pkg/upnp/upnp.go
Implement Pinhole Firewall traversal.
Changes:
- Replace UPNP Implementation with https://github.com/huin/goupnp
- Use WANIPv6FirewallControl to expose Services to the Internet
Consumer Routers (in my case a FritzBox) only allow port forwarding for your own device when using the IGD:1 (Internet Gateway Device: A UPNP role allows control over  router and similar devices). You can disable this security feature on other devices, but not on Fritz Boxes, which are quite popular in Germany.
After messing around with it a bit I found out that the IGD:2  WANIPv6FirewallControl control endpoints work much in the same way like port forwarding but my FritzBox does not check the origin of the forwarding request.
We also need to implement Lease Refreshing. It is unclear why it was missing in the …
=> Use IGD:2 and Pinhole Port Forwarding

cmd/kube-vip.go, pkg/cluster/cluster.go, pkg/cluster/service.go, pkg/kubevip/config_manager.go, pkg/manager/instance.go, pkg/manager/service_egress.go, pkg/vip/address.go, pkg/vip/util.go, testing/e2e/e2e_test.go
This PR adds auto subnet discovery for services deployed in ARP mode.
As for now all service VIP addresses have subnet of /32 and /128 for IPv4 and IPv6 respectively, if `vip_cidr` is not defined. After this changes if `vip_address` was not provided in config and `vip_cidr` will be set to `auto,auto` (first value is for IPv4, second for IPv6 addresses) kube-vip will try to find suitable subnet based on addresses available on the `vip_servicesinterface`. This is complementary to #926 . 
Example:
Config:
vip_servicesinterface: "eth0"
vip_cidr: "auto,auto"
Interface on the node:
```
14: eth0@if15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
link/ether 02:42:ac:12:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
inet 172.18.0.4/16 brd 172.18.255.255 scope global …
```
=> Added auto subnet discovery for services in ARP mode

Makefile, pkg/manager/watch_endpoints.go, testing/e2e/services/tests.go
For some reason the endpoint watcher had a check that meant that when "local" endpoints went to 0 then it would stop being part of the leader election, however it appears that it was wrapped with only being allowed when routing mode was enabled. This has broken a few things.
This make sense @p-strusiewiczsurmacki-mobica
=> Services aren't removed when there are no endpoints.

pkg/manager/node_labeling.go
As reported in the issue #863, nodelabel is missing sometimes.
for example, if the VIP is already associated with a node and you delete the kube-vip pods, once they're re-created, there's a good chance that none of your nodes will include the kube-vip/has-ip=xx label.
As a result, the existence of this label is unreliable.
The aim of this change is to ensure that the nodelabel is always added.
=> Ensuring nodelabel will be always present

pkg/manager/watch_services.go, testing/services/main.go, testing/services/pkg/deployment/kind.go, testing/services/pkg/deployment/kubernetes.go, testing/services/pkg/deployment/services.go, testing/services/pkg/deployment/tests.go
The golang-ci linter was complaining about unused variables, which resulted in a fix that ended up with long running references to objects. This returns it back to its original behaviour and fixes the linting issue.
Fixes #1028
=> Fixes an issue with watchers having an old reference

cmd/kube-vip.go
During investigating another issue I found a minor bug:
`log.SetLogLoggerLevel` is only called  in `init()` and `vip_loglevel` env var is never used so is it impossible to use it to change logging level. This should fix that.
=> Fixed ENV log level setting

pkg/bgp/peers.go, pkg/bgp/peers_test.go, pkg/bgp/types.go
=> You can now specify the port as the fifth argument to peer config

cmd/kube-vip-manifests.go, cmd/kube-vip.go, pkg/bgp/peers.go, pkg/bgp/peers_test.go, pkg/bgp/types.go
Fixes #912 
IPv6
```
~/kube-vip$ go run . manifest pod --address ip6only.me --interface eth0 --arp
...
- name: vip_cidr
value: "128"
- name: address
value: ip6only.me
```
IPv4
```
~/kube-vip$ go run . manifest pod --address ip4.me --interface eth0 --arp
...
- name: vip_cidr
value: "32"
- name: address
value: ip4.me
```
=> Resolver, this will ensure that an address that is not an IP address is resolved first to determine the CIDR

pkg/vip/address.go
This should fix #1052 
In case someone uses DualStack cluster but provides `vip_cidr` only for IPv6 addresses (e.g. `vip_cidr: "128"`) kube-vip, when IPv4 service is used,  tries to create a mask with `net.CIDRMask(128, 32)` which results in `nil` pointer and causes panic later.
This PR fixes this by checking if provided `vip_cidr` is not greater than max for IP family and using max value if so (e.g. if someone will try to set mask 128 for IPv4 service, ~~a warning will be logged and a mask of 32 will be used)~~ error will be returned.
Also added missing mutex locks when setting the mask itself.
=> Fixed network mask setting function

cmd/kube-vip.go, pkg/kubevip/config_environment.go, pkg/kubevip/config_envvar.go, pkg/kubevip/config_generator.go, pkg/kubevip/config_types.go, pkg/manager/manager.go
The env variable `health_check_port` as long an `!= 0` and `> 1024` will enable a health check on `/healthz`.. be aware that kube-vip uses `hostNetwork` so it would be easy for a port conflict.
=> This adds a health check

pkg/loadbalancer/ipvs.go
This PR should fix #875 and #895
It turned out that the AddBackend function was called and it tried to acquire mutex that was already locked, so the backend was never re-added.
=> Fixed IPVS backend re-add

pkg/manager/services.go, pkg/manager/servicesLeader.go, pkg/manager/watch_endpoints.go, pkg/manager/watch_services.go
This **should** fix #998 and #953
While working on the BGP changes I've noticed that services are not properly updated in BGP mode, so decided to give it a go. Tested this in BGP, ARP and RT modes and it seems to work just fine now.
Main changes:
- Added missing status reset to the existing `event.Modified` check.
- Changed the way `fetchServiceAddresses` works - it will now check if IPv4 or IPv6 provided in `s.Spec.LoadBalancerIP` is different from the same family IP address in `s.Status.LoadBalancer.Ingress` and if so will use it to update the address.
- Added mutex for service leader election - in case of update it sometimes happened that the restarted leader (on the same node) tried to acquire service lease before the stopped leader was able to fully step down. This seems to prevent …
=> Fixed service update in BGP and ARP mode

pkg/manager/instance.go, pkg/manager/manager_table.go, pkg/manager/watch_endpoints.go, testing/e2e/etcd/kube-etcd-vip.yaml.tmpl, testing/services/pkg/deployment/kubernetes.go
Recently we have discovered that kube-vip was unable to remove local-endpoint related route if 2 services referenced same pod (endpoint) and pod was deleted and recreated on another node. This should be fixed by this change.
Same happened if there were 2 services referencing same endpoint present on route cleareance at kube-vip start. That should be fixed as well.
=> Fixed route deletion issue when 2 services referenced same endpoint

pkg/backend/backend.go, pkg/cluster/cluster.go, pkg/cluster/clusterLeaderElection.go, pkg/cluster/service.go, pkg/cluster/singleNode.go, pkg/loadbalancer/ipvs.go, pkg/manager/manager_arp.go, pkg/manager/node_labeling.go, pkg/sysctl/sysctl.go, pkg/vip/address.go
I think this should fix the followup issue described in [the comment](https://github.com/kube-vip/kube-vip/issues/895#issuecomment-2702888317) in #895
Upon investigation it turned out that when kube-vip tries to delete IPVS loadbalancer it tries to close `nil` channel which results in panic and pre-mature exit. So I added initialization for this channel.
```
2025/03/10 12:25:02 INFO IPVS Loadbalancer enabled version=" 1.2.1"
2025/03/10 12:25:02 INFO sysctl set net.ipv4.vs.conntrack to 1
2025/03/10 12:25:02 INFO sysctl set net.ipv4.ip_forward to 1
2025/03/10 12:25:02 INFO layer 2 broadcaster starting
2025/03/10 12:25:02 DEBUG layer 2 update ip=10.0.1.10 interface=eth0 ms=3000
2025/03/10 12:25:02 INFO Kube-Vip is watching nodes for control-plane labels
2025/03/10 12:27:29 INFO Received …
```
=> Fixed IPVS deletion issues

pkg/kubevip/config_generator.go
While moving over to using the RBAC manifest generator, this stood out as a clear typo.
=> fix: s/endoints/endpoints/ in RBAC manifest generation code

.github/workflows/release.yaml
This change relies on `docker/metadata-action` to generate the appropriate labels.
Fixes #1044
=> feat: Add opencontainers annotations during release

pkg/kubevip/config_generator.go
As written, the RBAC manifest generator produces a rule that looks like:
```yaml
- apiGroups:
- ""
resources:
- services
- endpoints
verbs:
- list
- get
- watch
- endpoints
```
The very last line of this snippet, "endpoints", doesn't seem correct. This can be checked with the command `kubectl api-resources --verbs=endpoints`, which will show all resource types for which `endpoints` is a valid verb. In my cluster none exist. Based on the hand-written manifest published [here](https://github.com/kube-vip/website/blob/main/content/manifests/rbac.yaml#L19), I think this is supposed to be "update". This PR adjusts the RBAC manifest generation accordingly.
=> Replace invalid verb "endpoints" with "update"

pkg/manager/servicesLeader.go, pkg/manager/watch_endpoints.go, pkg/manager/watch_services.go, test.sh, testing/services/main.go, testing/services/pkg/deployment/kind.go, testing/services/pkg/deployment/kubernetes.go, testing/services/pkg/deployment/services.go, testing/services/pkg/deployment/tests.go
This PR introduces 2 changes:
1. It moves `configuredRoutes` maps into `serviceContext` struct. This is rather minor change that might simplify some things - like e.g. instead of remembering to delete the value from the `configuredRoutes` map it is sufficient to delete the service whatsoever sometimes. Additionally fixed some encapsulation.
2. It fixes the `service-tests` target. It turned out that there were a few issues in the tests (e.g. incorrect local address was found so the test server was reachable from the kind cluster, resulting in no traffic to/from loadbalancer/egress etc.). All tests should work fine now. Also, if any issue will occur the test will now explicitly fail in the CI.
Important info:
When running the `service-tests` target the test will try to find an interface …
=> Fixed service-tests + minor changes

pkg/manager/services.go, pkg/manager/watch_endpoints.go
As I am currently working on BGP e2e-tests I found that some current changes created a deadlock when trying to remove BGP routes upon service deletion. This should be fixed with this small PR.
=> Fixed BGP clear deadlock

Makefile, pkg/manager/endpoints.go, pkg/manager/endpoints_bgp.go, pkg/manager/endpoints_generic.go, pkg/manager/endpoints_routing_table.go, pkg/manager/watch_endpoints.go, pkg/manager/watch_services.go, pkg/vip/arp.go, testing/e2e/ip.go, testing/services/pkg/deployment/services.go, testing/services/pkg/deployment/tests.go
This PR moves code from the `manager/endpoint_watcher.go` to separate entity and additional interfaces. This is mostly just a first step and an example for achieving better readability of the code as I started discussion about his topic here: #1102 
Instead of just one big event loop I've decided to move that code to separate entity `Processor` in `manager/endpoints.go`. I've also moved some code to separate functions as I believe it's easier to understand that.
`Processor` uses interfaces `EndpointWorker` which can be instantiated into `Generic`, `BGP` or `RoutingTable` depending on the kube-vip's mode. This eliminates the need for  the mode-related conditional statements. Additionally any change that is relevant only to one of the modes will not affect any other mode.
Next steps for …
=> Refactoring endpoint-watcher code

pkg/backend/backend.go, testing/e2e/e2e_bgp_test.go, testing/e2e/e2e_rt_test.go, testing/e2e/e2e_test.go, testing/e2e/kube-vip-routing-table.yaml.tmpl, testing/services/pkg/deployment/services.go, testing/services/pkg/deployment/tests.go
This PR is a folloup to #1206 
It removes insecure client altogether in favor of adding additional certSANs to the kind cluster. 63 addresses (or less, if the address will fall out of the docker's interface CIDR)  will be added to the certs starting from the docker bridge address.
In case that there are many docker bridges (or other interfaces named `br-XXX`) the network interface for RT tests has to be provided with NETWORK_INTERFACE=<name> env variable similar to what's described in #1188
=> Removed insecure client use in E2E tests

.github/workflows/ci-pull-request.yaml, pkg/etcd/election.go, pkg/etcd/election_test.go, testing/e2e/e2e_bgp_test.go, testing/e2e/e2e_rt_test.go, testing/e2e/e2e_test.go, testing/e2e/ip.go, testing/e2e/kube-vip-bgp.yaml.tmpl, testing/e2e/kube-vip-hostname.yaml.tmpl, testing/e2e/kube-vip-routing-table.yaml.tmpl, testing/e2e/kube-vip.yaml.tmpl, testing/e2e/logs.go, testing/services/main.go, testing/services/pkg/deployment/kubernetes.go, testing/services/pkg/deployment/tests.go
This PR introduces logs gathering for the CI + some minor fixes as I am trying to stabilize the CI tests.
Logs of all kube-vip pods + kube-vip-cloud-controller pods (if used) + json list of services, leases and pods are currently being saved.
I have re-enabled parallel test execution as I would like to gather some more logs of CI errors.
=> Added logs as CI artifact
